export default {
  button: "button",
  data: {
    card: "data-card",
    color: "data-color",
    group: "data-group",
    "group-action": "data-group-action",
    "group-name": "data-group-name",
    id: "data-id",
    print: "data-print",
    "range-pos": "data-range-pos",
    section: "data-section",
    snake: "data-snake",
    state: "data-state",
    setting: "data-setting",
    type: "data-type",
  },
  aria: {
    controls: "aria-controls",
    expanded: "aria-expanded",
    haspopup: "aria-haspopup",
    live: "aria-live",
    selected: "aria-selected",
  },
};
